name: Deploy

on:
  push:
    branches:
      - master

jobs:
  frontend:
    name: Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the Docker Image
        uses: whoan/docker-build-with-cache-action@v6
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: apollusia/frontend
          image_tag: latest
          dockerfile: apps/frontend/Dockerfile
      - name: Deploy to Rancher
        uses: sekassel-research/actions-rancher-update@v3.0.0
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.RANCHER_CLUSTER }}
          project_id: ${{ secrets.RANCHER_PROJECT }}
          namespace: apollusia
          deployment: frontend
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/apollusia/frontend:latest
  backend:
    name: Backend
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build the Docker Image
        uses: whoan/docker-build-with-cache-action@v6
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: ${{ secrets.DOCKER_REGISTRY }}
          image_name: apollusia/backend
          image_tag: latest
          dockerfile: apps/backend/Dockerfile
      - name: Deploy to Rancher
        uses: sekassel-research/actions-rancher-update@v3.0.0
        with:
          rancher_url: ${{ secrets.RANCHER_URL }}
          rancher_token: ${{ secrets.RANCHER_TOKEN }}
          cluster_id: ${{ secrets.RANCHER_CLUSTER }}
          project_id: ${{ secrets.RANCHER_PROJECT }}
          namespace: apollusia
          deployment: backend
          docker_image: ${{ secrets.DOCKER_REGISTRY }}/apollusia/backend:latest
