name: Test

on:
  push:
    branches:
        - master
  pull_request:

jobs:
  lint-test:
    name: Lint ${{ matrix.app }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        app:
          - frontend
          - backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up pnpm
        uses: pnpm/action-setup@v3
        with:
          version: latest
      - name: Set up Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Lint
        run: pnpm run lint:${{ matrix.app }} --fix
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: Fix lint problems'
      - name: Test
        run: pnpm run test:${{ matrix.app }}
