name: Test

on:
  push:
    branches:
        - master
  pull_request:

jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest
      - name: Set up Node.js LTS
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
          cache: 'pnpm'
          cache-dependency-path: pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
  audit:
    name: Audit
    runs-on: ubuntu-latest
    needs:
      - setup
    steps:
      - name: Audit
        run: pnpm audit
  lint:
    name: Audit ${{ matrix.app }}
    runs-on: ubuntu-latest
    needs:
      - setup
    strategy:
      matrix:
        app:
          - frontend
          - backend
    steps:
      - name: Lint
        run: pnpm run lint:${{ matrix.app }}
  test:
    name: Test ${{ matrix.app }}
    runs-on: ubuntu-latest
    needs:
      - setup
    strategy:
      matrix:
        app:
          - frontend
          - backend
    steps:
      - name: Test
        run: pnpm run test:${{ matrix.app }}
